spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb_sec?currentSchema=public
    username: postgres
    password: passer
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql:true

server:
  port: 8081

#31:49
springdoc:
  api-docs.path: /api-docs 
  swagger-ui.path: /swagger-ui-custom.html